### ISSUE TITLE
Error: you must specify a custom media type in the 'Accept' header

### ISSUE THREAD

**Issue by petertulala** [octokit/request-action#100]
Hi. I have the following workflow step:
```
  createRepoUsingTemplate:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: create_repo_using_template
        with:
          route: POST /repos/TEMPLATE_OWNER/TEMPLATE_REPO/generate
          owner: OWNER
          name: NAME
          private: true
          accept: 'application/vnd.github.baptiste-preview+json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Even though I provided the Accept header as required by the [preview notice](https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template), the request fails with HTTP code `415` and I'm getting the following error:
`Error: If you would like to help us test the Repository Templates API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.`

When I manually call the HTTP request, everything works as expected:
```
POST https://api.github.com/repos/TwoDigits/url-shortener/generate
Accept: application/vnd.github.baptiste-preview+json
Authorization: Basic .....
Content-Type: application/json

{
  "owner": "OWNER",
  "name": "NAME"
}
```
```
Response code: 201 (Created); Time: 1861ms; Content length: 6500 bytes
```

**Comment by gr2m** [comment]
That's not how you can set an accept header, can you try this instead?

```yml
          mediaType:
            previews: ["baptiste"]
```

**Comment by petertulala** [comment]
> That's not how you can set an accept header, can you try this instead?
> 
> ```yaml
>           mediaType:
>             previews: ["baptiste"]
> ```


I've already tried that. But that ends up with a _startup failure_:
```
The workflow is not valid. .github/workflows/createRepo.yml (Line: 35, Col: 13): A mapping was not expected
```

**Comment by gr2m** [comment]
sorry, I forgot, stupid YAML. We have an example in the docs for a similar case, you need to set object values using a multi-line string, like so 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/39992/119877382-d2494880-bedd-11eb-87a0-477deda7668b.png">

Try this

```yml
          mediaType: |
            previews:
              - baptiste
```
