### ISSUE TITLE
Label does not exist

### ISSUE THREAD

**Issue by robingenz** [octokit/request-action#118]
First of all, thanks for this helpful GitHub action! 

I want to use this action to delete a specific label whenever a comment is created on an issue.
The label is: `needs: reply`.

This is my workflow:

```yml
name: Remove needs-reply label

on:
  issue_comment:
    types:
      - created

jobs:
  needs-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-reply label
        uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: 'needs: reply'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

I get the following error when running the action: 
```
Error: Label does not exist
```

(see this [example](https://github.com/robingenz/capacitor-firebase-authentication/actions/runs/1201236306))

The follwing request works:

```
curl --location --request DELETE 'https://api.github.com/repos/{user}/{repo}/issues/{issue}/labels/needs: reply' \
--header 'Authorization: token {token}'
```

For this reason, I assume that the error lies with the action.
Please let me know if you need more information.
Thank you very much!

**Comment by gr2m** [comment]
You get the error when the label no longer exists on the issue. Try running the `curl` command twice to replicate.

Does the action work the first time? My guess is that the action is run again after the label was removed. You can add an `if:` condition to the step or the job to make sure it doesn't.

If it fails the first time, can you create a minimal public repository to replicate the problem? I'll have a look

**Comment by robingenz** [comment]
I get the error even if the label still exists.
If I call the label `needs-reply` (for example), then it works as desired. The problem only occurs if there is a colon/space in the name.

I created a minimal public repository: [robingenz/octokit-request-action-issues-118](https://github.com/robingenz/octokit-request-action-issues-118).
This is my demo issue: https://github.com/robingenz/octokit-request-action-issues-118/issues/1
I added the label `needs-reply` and commented a few minutes later.
The workflow was executed (see [here](https://github.com/robingenz/octokit-request-action-issues-118/runs/3518800519)) and returned the following error message:
```
 Error: Label does not exist
```
The label is still present.

**Comment by gr2m** [comment]
> I created a minimal public repository: [robingenz/octokit-request-action-issues-118](https://github.com/robingenz/octokit-request-action-issues-118).

thanks!

> The problem only occurs if there is a colon/space in the name.

that very much sounds like a YAML problem 😌

You see how it says `label: [object Object]`? It should say `label: "needs: reply"` instead.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/39992/132137819-e9731ad0-be4c-4a6d-bd7c-790142e0b66f.png">

It's likely related to how we load the YAML config here:

https://github.com/octokit/request-action/blob/8609a6a9746eab4dee382f156583a7ba4e13ca04/index.js#L66

Here is a test case to confirm my assumption

https://runkit.com/gr2m/octokit-request-action-118

I'm open to ideas how to fix it. The reason why we do load value this way is that some parameters need to be set to objects, that's why we have the complex example in the readme with this line:

```yml
          output: | # The | is significant!
```

I think you can probably workaround the problem you are having by doing the following

```diff
-          label: 'needs: reply'
+          label: |
+            |
+              needs: label
```

Can you give that a try?

Ideally we would support the `label: 'needs: reply'` out of the box. But I'm not sure how to be sure that the user didn't intend to send `label: { needs: 'reply' }`

**Comment by gr2m** [comment]
maybe there is some YAML escape syntax that we can recommend to use for cases such as yours? I'm not super familiar with YAML though, not sure what the correct one would be, I always get lost in the YAML spec

**Comment by robingenz** [comment]
Thank you for pointing this out.
I am also not very familiar with YAML.   




```diff
-          label: 'needs: reply'
+          label: |
+            |
+              needs: label
```
Unfortunately, this did not work ([workflow run](https://github.com/robingenz/octokit-request-action-issues-118/runs/3527025647) / [comment](https://github.com/robingenz/octokit-request-action-issues-118/issues/1#issuecomment-913788970)).

I also tried:
```yml
label: >
  needs: reply

label: >-
  needs: reply

label: "
  needs: reply"

label: |-
  needs: reply
```
I couldn't find any YAML escape syntax so far.

I will look for other possible solutions over the weekend. 
Please let me know if you have any other ideas.

**Comment by gr2m** [comment]
Hmm at least the workflow run output looks correct:
https://github.com/robingenz/octokit-request-action-issues-118/runs/3527025647#step:2:16

<img width="940" alt="image" src="https://user-images.githubusercontent.com/39992/132255650-c1302dc1-9ede-409f-93db-d95b25381e93.png">

Can you please [enable DEBUG logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging) by adding the `ACTIONS_STEP_DEBUG` secret and setting it to `true`

**Comment by gr2m** [comment]
It seems that the string now is

```
needs: reply

```

With a line break at the end.

Can you try this please?

```yml
label: |
  |-
    needs: reply
```

**Comment by robingenz** [comment]
I enabled the debug logs.

However, the line break [did not move](https://github.com/robingenz/octokit-request-action-issues-118/runs/3527613745?check_suite_focus=true#step:2:63). 😄

**Comment by gr2m** [comment]
At least now I'm positive that there is a line break at the end:
https://github.com/robingenz/octokit-request-action-issues-118/runs/3527613745?check_suite_focus=true#step:2:113

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/39992/132257618-c0dfa096-9089-4f7c-bec1-05892823fe1f.png">

**Comment by robingenz** [comment]
My temporary workaround:
```yml
name: Remove needs-reply label

on:
  issue_comment:
    types:
      - created

jobs:
  needs-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-reply label
        run: |
          curl --request DELETE \
          --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/needs%3A%20reply' \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
```
Just in case anyone else is looking for a quick fix.
