### ISSUE TITLE
Performing a `deployment` request does not trigger action

### ISSUE THREAD

**Issue by kbiedrzycki** [octokit/request-action#12]
Hey,

I am trying to build CI/CD pipeline using GitHub Actions and I wanted to split CI and CD flows into separate files. To do this I need to communicate them somehow, and because GitHub does not allow to tell that one workflow is dependent on another I wanted to use workflow triggers with webhook events - to be more precise - deployment event. 

So, in my CI flow, I've added a job that triggers staging deployment:
```yml
  staging_deployment:
    if: github.event_name == 'pull_request' && (startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/'))
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Trigger staging deployment
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          required_contexts: "[]"
          environment: "staging"
          ref: ${{ github.head_ref }}
```

the job should start only for specific branches and also it is triggered after `integration` job finishes. All of these works fine, however, the listener is not triggered, even though listener is set to `on: deployment`. What is weird, when I perform regular cURL request, everything works fine. Any clue what might be an issue?
