### ISSUE TITLE
Search issue with query

### ISSUE THREAD

**Issue by KodaCHC** [octokit/request-action#135]
I use this call
```
      - name: API Call
        uses: octokit/request-action@v2.x
        id: get_issues_newfeatures
        with:
          route: GET /search/issues
          q: 'repo:org/repo'
          per_page: 100
```

I get this error: Unexpected input(s) 'q', 'per_page', valid inputs are ['route', 'mediaType']

The same if I want to use {org} and {repo}. is it possible to hide the warning?

Fount it. Sorry: https://github.com/octokit/request-action/issues/26
