### ISSUE TITLE
Pass over body to REST call

### ISSUE THREAD

**Issue by pc-ahrens** [octokit/request-action#140]
Hello there,

I've been trying to call the rest api of this to update the visibility of a repository:
https://docs.github.com/en/enterprise-server@3.1/rest/reference/repos#update-a-repository

However, every I am not able to pass a body to the route.

```
- uses: octokit/request-action@v2.1.4
  id: set_private
  with:
    route: PATCH /repos/$ORG/$REPO
    mediaType: application/vnd.github.v3+json
    body: ${{ toJSON(env.REQUEST_BODY) }}
  env:
    GITHUB_TOKEN: ${{ secrets.SITE_ADMIN_PAT }}
    ORG: ${{ fromJSON(steps.issue_body_parser.outputs.payload).Organisation }}
    REPO: ${{ fromJSON(steps.issue_body_parser.outputs.payload).Repository }}
    REQUEST_BODY: |
      '{ "visibility": "private" }'
```

--> Error: Cannot read property 'map' of undefined

Could you please support me with this? How can I pass over parameters in the body to a REST endpoint?

Best regards
Per Ahrens
