### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by oeed** [octokit/request-action#175]
I'm trying to download the contents of a file from another repo and I'm getting a rather unhelpful error. Nothing I've tried seems to help.

Action:

```
- name: Download Desktop Client Types
  uses: octokit/request-action@v2.x
  id: get_desktop_client
  with:
    route: GET /repos/OWNER/REPO/contents/src/types/api.d.ts
    mediaType: application/vnd.github.raw
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
Run octokit/request-action@v2.x
GET /repos/OWNER/REPORT/contents/src/types/api.d.ts
> mediaType: application/vnd.github.raw

(node:15[9](https://github.com/SpalkLtd/content-hub/runs/7891226272?check_suite_focus=true#step:3:10)1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Cannot read property 'map' of undefined
```

**Comment by timrogers** [comment]
It's not clear to me how `map` is getting called, looking at the code for `octokit/request-action`.

Can you try following the instructions [here](https://github.com/octokit/request-action#debugging) to enable debug logging? I'm wondering if that might help us to get more context.

**Comment by oeed** [comment]
I ended up using action-script which led me to discover that the GitHub token I was using didn't have access to the repo (got a 404), so it's likely something handling that incorrectly.

**Comment by timrogers** [comment]
I was able to reproduce the issue with a minimal workflow file like this:


```
name: Download file without required permissions
on: workflow_dispatch

jobs:
  download_file:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: download_file
        with:
          route: GET /repos/{owner}/{repo}/contents/README.md
          mediaType: application/vnd.github.raw
          owner: github
          repo: github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I'll try to figure out what's going on.
