### ISSUE TITLE
Auto-paginated through responses spread over multiple pages

### ISSUE THREAD

**Issue by dhirschfeld** [octokit/request-action#181]
I'm trying to get tags associated with container images by hitting the below endpoint:
```yaml
  route: GET /orgs/{org}/packages/container/{container}/versions
```
* https://docs.github.com/en/rest/reference/packages#get-all-package-versions-for-a-package-owned-by-an-organization

When using this action the returned data appears to be truncated to 30 items!?!

Using the `gh` cli correctly returns all image ids/tags:
```bash
data=$(gh api -X GET --paginate "/orgs/${org}/packages/container/${container}/versions")
echo $data | jq 'map({(.id|tostring):  .metadata.container.tags}) | add'
```
Am I missing something obvious (e.g. a paginate argument) or is this a bug?

<details>
<summary><b><tt>action.yml</b></tt></summary>

```yaml
name: Get Image Tags
description: 'Returns the tags associated with a container image.'
inputs:
  repo:
    required: true
    type: string
  container:
    required: true
    type: string
  ghcr_token:
    required: true
outputs:
  images:
    description: "A mapping of image ids to image tags."
    value: ${{ steps.set_output.outputs.images }}
runs:
  using: "composite"
  steps:
    - id: parse_repo
      shell: bash
      run: |
        set -euox pipefail
        IFS='/' read owner repo <<< ${{ inputs.repo }}
        echo "::set-output name=org::${owner}"
        echo "::set-output name=container::${repo,,}/${{ inputs.container }}"
    - id: get_images
      # https://github.com/octokit/request-action
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ inputs.ghcr_token }}
      with:
        org: ${{ steps.parse_repo.outputs.org }}
        container: ${{ steps.parse_repo.outputs.container }}
        route: GET /orgs/{org}/packages/container/{container}/versions
    - id: set_output
      shell: bash
      run: |
        set -euox pipefail
        images=$(echo -e ${{ toJSON(steps.get_images.outputs.data) }} | jq -c 'map({(.id|tostring): .metadata.container.tags}) | add')
        echo "::set-output name=images::${images}"
```
</details>
