### ISSUE TITLE
Node.js 12 warnings

### ISSUE THREAD

**Issue by lgadalla-impinj** [octokit/request-action#193]
For a step using this action something like this:

```
      - name: Check to see if branch exists
        id: branch-exists
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/ref/${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
```
the code seems to work, but I keep getting warnings like this:

```
<jobname>
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: octokit/request-action
```

Is there a way around this, or at least a way to temporarily suppress the warning until this action is re-written for Node.js 16?
