### ISSUE TITLE
[BUG]: sensitive output (`actions/runners/registration-token`) can't be masked

### ISSUE THREAD

**Issue by dennisameling** [octokit/request-action#213]
### What happened?

Consider the following Actions config:

```
   - name: Generate Actions Runner token
      uses: octokit/request-action@v2.x
      id: generate-actions-runner-token
      with:
        route: POST /repos/{owner}/{repo}/actions/runners/registration-token
        owner: ${{ env.ACTIONS_RUNNER_ORG }}
        repo: ${{ env.ACTIONS_RUNNER_REPO }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_API_PAT }}

   - name: Set and mask Actions Runner token for next steps
     run: |
        # We need to mask the token first before setting it to an env variable
        echo "::add-mask::${{ fromJson(steps.generate-actions-runner-token.outputs.data).token }}"
        ACTIONS_RUNNER_TOKEN=${{ fromJson(steps.generate-actions-runner-token.outputs.data).token }}
        echo ACTIONS_RUNNER_TOKEN=$ACTIONS_RUNNER_TOKEN >> $GITHUB_ENV    
```

This actually exposes the token to the CI logs, as also reported in this issue: https://github.com/actions/runner/issues/475

![image](https://user-images.githubusercontent.com/17739158/208660644-4388c933-af82-487d-849c-96cae53d26d4.png)

You might want to add a warning about this to the README of this action or find another solution to hide this sensitive data. Thanks!

### Versions

octokit/request-action@v2.x

### Relevant log output

```shell
See above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
