### ISSUE TITLE
[FEAT]: Support onprem github api calls

### ISSUE THREAD

**Issue by gaurav517** [octokit/request-action#275]
### Describe the need

Can we please support onprem github api calls? 

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
try

```yml
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /
          baseurl: ${{ env.GITHUB_API_URL }}
```

If that works, could you send a pull request to update the README so others will know how to do it in future?
