### ISSUE TITLE
[BUG]: Attempting GET on a Github commit API fails

### ISSUE THREAD

**Issue by ajmmm** [octokit/request-action#276]
### What happened?

When attempting to use the action to perform a GET on the following API, the action fails:

```
...
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/commits/${{ github.sha }}/pulls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Attempted it a few different ways - even with a manually specified SHA.

### Versions

Octokit v2.x
Node 10.24 (RHEL 8)

### Relevant log output

```shell
/root/.cache/act/36476ce2c9b7795f/act/actions/octokit-request-action@v2.x/dist/index.js:1905
  static {
         ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
Error:   ❌  Failure - Main Get SHA pulls
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Error: exit status 1
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
🏁  Job failed
Error: exit status 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
