### ISSUE TITLE
[FEAT]: Add fail_on_error option to suppress failing 

### ISSUE THREAD

**Issue by Uzlopak** [octokit/request-action#288]
### Describe the need

I have a workflow, where i remove a label from a PR. It would be good to add an option to the action.yml which just outputs a warning and not a failure, so e.g. if the label is already removed it does not show an error in the overview. 

If we agree on the name of the option, I would provide a PR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andy-maier** [comment]
I would like to second this request. We have a workflow that determines whether a tag exists:
```
    - name: Determine whether release on Github exists for the pushed tag
      id: set-release-exists
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/releases/tags/${{ steps.set-tag.outputs.result }}
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
When the tag does not exist, the plugin errors out with 404, and the `continue-on-error: true` causes it to continue, so the functionality works. However, we get the 404 error reported in the actions summary, which looks bad.
