### ISSUE TITLE
How to call add Tag?

### ISSUE THREAD

**Issue by pilganchuk** [octokit/request-action#290]
I'm trying to add a lightweight tag (according this [doc](https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#create-a-tag-object)) on my commit, but I have an error...
The action:
```
      - uses: octokit/request-action@v2.x
        id: push_tag
        with:
          route: POST /repos/{owner}/{repo}/git/tags
          owner: novaittestteam
          repo: ntk.mob
          body: ${{ toJSON(env.REQUEST_BODY) }}
          mediaType: |
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUEST_BODY: |
            {"tag":"test","message":"Auto API Call","object":"4c64ded9bed5633f4918ea0284be44c4f85541c4","type":"commit","tagger":{"name":"AutoAPICall","email":"support@test.com"}}
```
```
The error:
< 422 322ms
Error: Invalid request.
```

"message", "object", "tag", "type" weren't supplied.

Where am I wrong? How can I see the whole response body returned from API?
