### ISSUE TITLE
[Question]: How to use this action with `POST /repos/{owner}/{repo}/check-runs`

### ISSUE THREAD

**Issue by mostlycloudysky** [octokit/request-action#291]
### What happened?

I have gone through the readme example and it looks like, check API does not work directly with the special GitHub Action Secret and it needs to be done through Github APP integration. Could you please clarify ? 

```
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: octokit
          repo: request-action
          name: "Test check run"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Versions

request-action@v2.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
