### ISSUE TITLE
[DOCS]: Clarify how to set body inputs

### ISSUE THREAD

**Issue by miguel-vila** [octokit/request-action#294]
### Describe the need

I had to look into the code in order to do pass `input` to a workflow dispatch invocation. And I'm not sure if I did it the way that's intended. The inputs section in the readme wasn't clear enough to me. Could we clarify that?

This is the invocation I ended up with:

```yml
- uses: octokit/request-action@v2.x
  if: contains(github.event.pull_request.labels.*.name, 'open-ar-pr')
  with:
    route: POST /repos/platform-common/api-registry/actions/workflows/bump-arlib-version.yml/dispatches
    mediaType: application/vnd.github.v3+json
    ref: main
  env:
    GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
    INPUT_INPUTS: |
      {
        "pr-number": "${{ github.event.pull_request.number }}",
        "version": "${{ steps.get-version.outputs.version }}"
      }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
I'd do

```yml
  with:
    route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
    owner: platform-common
    repo: repo
    workflow_id: bump-arlib-version.yml
    ref: main
    inputs: |
        pr-number: "${{ github.event.pull_request.number }}"
        version: "${{ steps.get-version.outputs.version }}"
```

You can see examples of how to pass object body parameters in the advanced README example. The `|` is significant in order for the value to be parsed as an object
