### ISSUE TITLE
set asset id on upload

### ISSUE THREAD

**Issue by soloturn** [octokit/request-action#49]
could you please add into the documentation how it would be possible to upload a "latest" asset with a changing file name, but same ID, a little like in https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447 ? i.e. the filename is package-1.0-qwers.zst, qwers beeing the git hash when it was built. the id should be "package" only.

**Comment by gr2m** [comment]
This action can only send 1:1 requests as they are documented, e.g. https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#upload-a-release-asset

```yml
      - uses: octokit/request-action@v2.x
        id: upload_release_asset
        with:
          route: POST /repos/{repository}/releases/{release_id}/assets
          repository: ${{ github.repository }}
          release_id: <release id here>
          headers: |
            content-type: application/zstd
          name: package-1.0-qwers.zst
          label: package
          data: <content of binary file>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

If you want to upload an asset to the latest release, you will need two requests. I'm also not sure if can set the `data` variable to the binary content of the file.

There are several actions dedicated to uploading a release asset, maybe one of them would be a better fit for your use case?

**Comment by tillkruss** [comment]
@gr2m: Would you have an example for me on how to read the binary file and set the `data` property?

**Comment by gr2m** [comment]
The `data` property is base64 encoded by default. Can you try setting the media type format to raw by adding the `mediaType` parameter?

```
        mediaType: |
            format: raw
```

That should set `outputs.[id].data` to the raw data content. But I didn't test it myself

See https://docs.github.com/en/rest/overview/media-types#repository-contents for more details on the media type format

**Comment by tillkruss** [comment]
Thanks, and do you have any hints for how to set the `data` value?

```yaml
 - uses: octokit/request-action@v2.x
    id: upload_release_asset
    with:
      route: POST /repos/{repository}/releases/{release_id}/assets
      data: ${{ readfile('foobar.zip') }}
```
