### ISSUE TITLE
How to pass a multi-line argument to request-action

### ISSUE THREAD

**Issue by sodre** [octokit/request-action#6]
I am trying to create a pull-request with a multi-line body comment using octokit/request-action. However, the `yaml.safeLoad` [call][call] is turning my multi-line string into a single line. 

  - Is there a way to bypass that behavior? 
  - Do you know how I can properly escape the multiline string so `yaml.safeLoad` will output what typed instead of converting it?

Here is what the action looks like in my workflow:
```yaml
...
      - name: Create pull-request against master
        uses: octokit/request-action@v2.x
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/:repository/pulls
          repository: ${{ github.repository }}
          title: Merge ght/master into master
          head: ght/master
          base: master
          body: |
            Modifications to ght/master were detected.
              - [ ] Review the changes
              - [ ] Fix the errors by committing back to ght/master
              - [ ] Do **not** use Squash or Rebase
              - [ ] Do **not** delete the ght/master branch
```

The log messages when that action runs looks like as follows:
```
POST /repos/:repository/pulls
> repository: sodre/turbo-memory
> title: Merge ght/master into master
> head: ght/master
> base: master
> body: Modifications to ght/master were detected. - [ ] Review the changes - [ ] Fix the errors by committing back to ght/master - [ ] Do **not** use Squash or Rebase - [ ] Do **not** delete the ght/master branch
< 201 1068ms
```

[call]: https://github.com/octokit/request-action/blob/a43ad662a5c7b9f83ff18ff5d40564f214c23925/index.js#L49

**Comment by sodre** [comment]
I tried many routes, what ended up working for me is adding an additional `|` to tell yaml.safeLoad, that it is actually reading a multi-line string.

```yaml
...
  body: |
    |
    My muti-line comment
      - [ ] a
      - [ ] b
...
```

**Comment by gr2m** [comment]
I'm glad you got it working! We added the `yaml.safeLoad` to allow parameters to be set to JSON strings, so object parameters can be supported. It sounds very odd that it removes the new lines ... your workaround looks odd to me, too. I feel like there should be proper way to do this, but I don't have the time to look into it myself right now, maybe you or someone else can dig into this?

**Comment by sodre** [comment]
@gr2m, I think the problem is simple to understand now. The values in the `with` section for `octokit/request-action`, are always interpreted as yaml documents, and not literally as strings.

I will try to create a simpler test case to reproduce the problem.

**Comment by uditgaurav** [comment]
A similar type of issue I'm facing:
My `if` condition is very larger in size and I want to write it in multiple lines. Is there any way to do that?
```yaml
      - name: Running all tests
        if: startsWith(github.event.comment.body, '/run-e2e-all') || startsWith(github.event.comment.body, '/run-e2e-first-test') || startsWith(github.event.comment.body, '/run-e2e-second-test') || startsWith(github.event.comment.body, '/run-e2e-third-test') || startsWith(github.event.comment.body, '/run-e2e-fourth-test') || startsWith(github.event.comment.body, '/run-e2e-fifth-test') || startsWith(github.event.comment.body, '/run-e2e-sixth-test') || startsWith(github.event.comment.body, '/run-e2e-seventh-test') || startsWith(github.event.comment.body, '/run-e2e-eighth-test') || startsWith(github.event.comment.body, '/run-e2e-nineth-test') || startsWith(github.event.comment.body, '/run-e2e-tenth-test')
        run: |
          echo "Hello all"
```
