### ISSUE TITLE
"{}" argument syntax in route does not work, ":" works

### ISSUE THREAD

**Issue by dzeyelid** [octokit/request-action#69]
The README shows sample codes with `{}` as an argument, but it does not work. The samples confuse users. I guess it's better to replace the syntax with `:`.

For example, 

```
# This does not work

- uses: octokit/request-action@v2.x
  id: get_latest_release
  with:
    route: GET /repos/{owner}/{repo}/releases/latest
    owner: octokit
    repo: request-action
```

```
# This works

- uses: octokit/request-action@v2.x
  id: get_latest_release
  with:
    route: GET /repos/:owner/:repo/releases/latest
    owner: octokit
    repo: request-action
```

Anyway, thanks for this great action!

Best regards,
