### ISSUE TITLE
Can this be revised to parse the JSON upon request?

### ISSUE THREAD

**Issue by winzig** [octokit/request-action#8]
Rather than having to follow every `request-action` step with a `gr2m/get-json-paths-action@v1.x` to parse it, would it be possible for this action to accept those parsing requests directly? E.g. 

```
- uses: octokit/request-action@v2.x
  id: get_latest_release
  with:
    route: GET /repos/:repository/releases/latest
    repository: ${{ github.repository }}
    tag_name: "data.tag_name"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- run "echo Latest Tag: ${{ steps.get_latest_release.outputs.tag_name }}"
```
