### ISSUE TITLE
Ignoring some errors

### ISSUE THREAD

**Issue by stefanloerwald** [octokit/request-action#86]
Hi,

I'm designing a workflow where I create a new repository. I'm using octokit/request-action to make the request:

```yml
    steps:
      - uses: octokit/request-action@v2.x
        id: create
        with:
          route: POST /orgs/{org}/repos
          org: my-org
          accept: 'application/vnd.github.v3+json'
          name: repo-name
          description: This is an automatically generated repo. Ignore me.
          visibility: private
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
```

This works fine, but there are situations where the repo already exists. In that case the above will return the error `Repository creation failed.: {"resource":"Repository","code":"custom","field":"name","message":"name already exists on this account"}`. Is there some way to ignore this error such that dependent jobs continue to execute? After all, the goal of having a repo with that name is fulfilled.

Thanks
Stefan
