### ISSUE TITLE
Upload release asset

### ISSUE THREAD

**Issue by cb80** [octokit/request-action#96]
Dear all,

I am trying to upload a binary file to a release. I have retrieved the release structure in a previous step called `rel`. This is what I have:
```
    - uses: octokit/request-action@v2.x
      with:
        route: POST ${{ fromJson(steps.rel.outputs.data).upload_url }}
        name: mybinary
        data: path/to/mybinary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It works great except that the uploaded file does not contain the bytes of the file. Instead it contains the string `path/to/mybinary`. So how can I actually upload a file?

PS: The whole pipeline is a little more complicated but I tried to condense it in a http://sscce.org/ manner.
